### ISSUE TITLE
Compiling with module support?

### ISSUE THREAD

**Issue by xianbaum** [enko/EmacsChocolateyPackage#14]
Is there a chance that this emacs package can be compiled with module support? (--with-modules) Is something preventing that?

From emacs INSTALL instructions file:

Use --with-modules to build Emacs with support for dynamic modules.
This needs a C compiler that supports '__attribute__ ((cleanup (...)))',
as in GCC 3.4 and later.

**Comment by xianbaum** [comment]
I just noticed these are precompiled packages from gnu -- perhaps I should check with the maintainer there. I'll close this. :)

**Comment by enko** [comment]
Hey @xianbaum 

I think the best way of actions would be writing to the [windows specific maillinglist](https://lists.gnu.org/mailman/listinfo/help-emacs-windows).

HTH

Tim
