### ISSUE TITLE
Prevent cmd windows from poping up

### ISSUE THREAD

**Issue by Silex** [enko/EmacsChocolateyPackage#15]
Hello,

It seems I cannot run Emacs without its associated dos windows poping up. Any idea what to investiguate?

It runs from C:\ProgramData\chocolatey\bin\emacs.exe

Kind regards,
Philippe

**Comment by enko** [comment]
If you dont want the command prompt you have to use `runemacs.exe`.

Please  let me know if that fixes that problem for you.

Thanks for using this package.

**Comment by Silex** [comment]
Ah thanks, that's perfect! 👍
