### ISSUE TITLE
bad checksum for 27.1

### ISSUE THREAD

**Issue by notuntoward** [enko/EmacsChocolateyPackage#18]
Hi, I'm getting a checksum error when I try to upgrade to emacs 27.1:

> **> choco upgrade emacs**
>
>
> Chocolatey v0.10.15
> Upgrading the following packages:
> emacs
> By upgrading you accept licenses for the packages.
> 
> You have emacs v26.3.0.20191219 installed. Version 27.1.0.20200820 is available based on your source(s).
> Progress: Downloading Emacs 27.1.0.20200820... 100%
> 
> Emacs v27.1.0.20200820 [Approved]
> emacs package files upgrade completed. Performing other installation steps.
> File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
> Error - hashes do not match. Actual value was 'CCDAA194D80B6D5C7D087267E2E57211EB98012FA135C917F1BA714D09E7F641'.
> Downloading emacs 64 bit
> from 'https://alpha.gnu.org/gnu/emacs/pretest/windows/emacs-27/emacs-27.1-x86_64-no-deps.zip'
> Progress: 100% - Completed download of C:\Users\scott\AppData\Local\Temp\chocolatey\Emacs\27.1.0.20200820\emacs-27.1-x86_64-no-deps.zip (47.15 MB).
> Download of emacs-27.1-x86_64-no-deps.zip (47.15 MB) completed.
> Error - hashes do not match. Actual value was 'CCDAA194D80B6D5C7D087267E2E57211EB98012FA135C917F1BA714D09E7F641'.
> ERROR: Checksum for 'C:\Users\scott\AppData\Local\Temp\chocolatey\Emacs\27.1.0.20200820\emacs-27.1-x86_64-no-deps.zip' did not meet 'dc00a3bd152d984f079472d2fb34af6ae4beb9bfef56162d6aa4a6685571900a' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
> The upgrade of emacs was NOT successful.
> Error while running 'C:\ProgramData\chocolatey\lib\Emacs\tools\chocolateyInstall.ps1'.
> See log for details.
> 
> Chocolatey upgraded 0/1 packages. 1 packages failed.
> See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
> 
> 
> Failures
> - emacs (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\Emacs\tools\chocolateyInstall.ps1'.
> See log for details.

**Comment by enko** [comment]
Yeah, I also get this checksum now, strangely the pipeline succeeded in installing the package. I'll update all the checksums

**Comment by enko** [comment]
Also let's continue discussion in #16
