### ISSUE TITLE
Upgrade to 27.2

### ISSUE THREAD

**Issue by fpvmorais** [enko/EmacsChocolateyPackage#22]
Hi,

We already have binaries for 27.2. Can you please update the chocolatey package?
Thanks

https://alpha.gnu.org/gnu/emacs/pretest/windows/emacs-27/emacs-27.2-x86_64-installer.exe

**Comment by tekai** [comment]
27.2 is also available at https://ftp.gnu.org/gnu/emacs/windows/emacs-27/

**Comment by enko** [comment]
Done with #23 

Have Phun!

**Comment by enko** [comment]
Release has landed: https://community.chocolatey.org/packages/Emacs/27.2.0.20210423
