### ISSUE TITLE
Update Upstream URL for 24.5

### ISSUE THREAD

**Issue by vschum** [enko/EmacsChocolateyPackage#6]
Is it possible to push updated nupkg sfor older releases of Emacs? The older nupkg files have references to broken upsteam URLs.

**Comment by enko** [comment]
Hey @vschum,

I don't know if that is possible, but will try it that weekend.

greetings

Tim

**Comment by vschum** [comment]
Cool, thanks for the update. If it isn't possible I would suggest purging
those versions, since they're effectively broken.

**Comment by enko** [comment]
Hey @vschum ,

I managed to publish a new release of 24.5:

https://chocolatey.org/packages/Emacs/24.5.0.20191123

Maybe you can give it a try

greetings

Tim

**Comment by vschum** [comment]
This worked for me. Thanks!

**Comment by enko** [comment]
You are welcome!
